export const MOCK_PROPERTIES = [
  {
    _id: "1",
    title: "Luxury 4-Bedroom Duplex",
    location: "Lekki, Lagos",
    price: 250000000,
    status: "available" as const,
    description: "A stunning duplex with modern amenities and premium finishes.",
    thumbnail: "/luxury-4-bedroom-duplex.jpg",
    images: ["/luxury-duplex-exterior.jpg", "/luxury-living-room.png", "/luxurious-master-bedroom.png"],
    highlights: {
      bedrooms: 4,
      bathrooms: 3,
      sqft: 5000,
      parking: 2,
    },
    amenities: ["Swimming Pool", "Gym", "Security", "Garden", "Smart Home System"],
    land_size: "1,200 sqm",
    document_status: "Governor Consent",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    map_coordinates: { lat: 6.44, lng: 3.34 },
    agent_contact: {
      phone: "+234 (0) 123 456 7890",
      whatsapp: "+234 (0) 123 456 7890",
      email: "agent@primecrest.com",
    },
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    _id: "2",
    title: "3-Bedroom Terraced House",
    location: "Ikoyi, Lagos",
    price: 180000000,
    status: "available" as const,
    description: "Modern terraced house in a secure gated community.",
    thumbnail: "/3-bedroom-terraced-house.jpg",
    images: ["/terraced-house-exterior.jpg", "/cozy-dining-nook.png", "/cozy-bedroom.png"],
    highlights: {
      bedrooms: 3,
      bathrooms: 2,
      sqft: 3500,
      parking: 1,
    },
    amenities: ["24/7 Security", "Spacious Living", "Modern Kitchen"],
    land_size: "800 sqm",
    document_status: "C of O",
    video_url: undefined,
    map_coordinates: { lat: 6.43, lng: 3.33 },
    agent_contact: {
      phone: "+234 (0) 123 456 7890",
      whatsapp: "+234 (0) 123 456 7890",
      email: "agent@primecrest.com",
    },
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    _id: "3",
    title: "Commercial Plot - Mainland",
    location: "VI, Lagos",
    price: 150000000,
    status: "sold" as const,
    description: "Prime commercial property perfect for offices or retail.",
    thumbnail: "/commercial-plot.jpg",
    images: ["/commercial-plot.jpg", "/business-district.jpg"],
    highlights: {
      bedrooms: 0,
      bathrooms: 0,
      sqft: 8000,
      parking: 0,
    },
    amenities: ["High Visibility", "Main Road Access"],
    land_size: "2,000 sqm",
    document_status: "Governor Consent",
    video_url: undefined,
    map_coordinates: { lat: 6.45, lng: 3.35 },
    agent_contact: {
      phone: "+234 (0) 123 456 7890",
      whatsapp: "+234 (0) 123 456 7890",
      email: "agent@primecrest.com",
    },
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    _id: "4",
    title: "Luxury 5-Bedroom Penthouse",
    location: "Banana Island, Lagos",
    price: 450000000,
    status: "available" as const,
    description: "Exclusive penthouse with stunning city views and premium amenities.",
    thumbnail: "/luxury-penthouse.png",
    images: ["/penthouse-exterior.jpg", "/penthouse-view.jpg", "/master-suite.jpg"],
    highlights: {
      bedrooms: 5,
      bathrooms: 4,
      sqft: 6500,
      parking: 3,
    },
    amenities: ["Infinity Pool", "Gym", "Cinema", "Wine Cellar", "Rooftop Terrace"],
    land_size: "1,500 sqm",
    document_status: "Governor Consent",
    video_url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    map_coordinates: { lat: 6.42, lng: 3.32 },
    agent_contact: {
      phone: "+234 (0) 123 456 7890",
      whatsapp: "+234 (0) 123 456 7890",
      email: "agent@primecrest.com",
    },
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    _id: "5",
    title: "2-Bedroom Apartment",
    location: "Surulere, Lagos",
    price: 75000000,
    status: "available" as const,
    description: "Affordable and comfortable apartment in a vibrant neighborhood.",
    thumbnail: "/2-bedroom-apartment.jpg",
    images: ["/modern-apartment-exterior.png", "/cozy-apartment-living-room.png"],
    highlights: {
      bedrooms: 2,
      bathrooms: 1,
      sqft: 1200,
      parking: 1,
    },
    amenities: ["Good Neighbourhood", "Easy Access"],
    land_size: "200 sqm",
    document_status: "C of O",
    video_url: undefined,
    map_coordinates: { lat: 6.48, lng: 3.31 },
    agent_contact: {
      phone: "+234 (0) 123 456 7890",
      whatsapp: "+234 (0) 123 456 7890",
      email: "agent@primecrest.com",
    },
    created_at: Date.now(),
    updated_at: Date.now(),
  },
  {
    _id: "6",
    title: "Estate Plot - Ajah",
    location: "Ajah, Lagos",
    price: 85000000,
    status: "available" as const,
    description: "Residential plot in a planned estate community.",
    thumbnail: "/residential-plot-estate.jpg",
    images: ["/estate-community.jpg", "/green-space.jpg"],
    highlights: {
      bedrooms: 0,
      bathrooms: 0,
      sqft: 5000,
      parking: 0,
    },
    amenities: ["Gated Community", "Schools Nearby", "Hospital Access"],
    land_size: "600 sqm",
    document_status: "Governor Consent",
    video_url: undefined,
    map_coordinates: { lat: 6.39, lng: 3.4 },
    agent_contact: {
      phone: "+234 (0) 123 456 7890",
      whatsapp: "+234 (0) 123 456 7890",
      email: "agent@primecrest.com",
    },
    created_at: Date.now(),
    updated_at: Date.now(),
  },
]
