-- Create settings table
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  site_name TEXT NOT NULL DEFAULT 'PrimeCrest Realties',
  site_description TEXT NOT NULL DEFAULT 'Premium Real Estate Solutions',
  contact_email TEXT NOT NULL DEFAULT 'info@primecrest.com',
  contact_phone TEXT NOT NULL DEFAULT '+234 (0) 123 456 7890',
  contact_whatsapp TEXT NOT NULL DEFAULT '+234 (0) 123 456 7890',
  office_address TEXT NOT NULL DEFAULT 'Lagos, Nigeria',
  business_hours TEXT NOT NULL DEFAULT 'Mon - Fri: 9:00 AM - 6:00 PM',
  maintenance_mode BOOLEAN NOT NULL DEFAULT false,
  allow_property_submissions BOOLEAN NOT NULL DEFAULT true,
  require_email_verification BOOLEAN NOT NULL DEFAULT true,
  auto_approve_properties BOOLEAN NOT NULL DEFAULT false,
  max_upload_size INTEGER NOT NULL DEFAULT 10,
  support_email TEXT NOT NULL DEFAULT 'support@primecrest.com',
  privacy_policy_url TEXT NOT NULL DEFAULT '/privacy',
  terms_url TEXT NOT NULL DEFAULT '/terms',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default settings if not exists
INSERT INTO settings (id, site_name)
VALUES (1, 'PrimeCrest Realties')
ON CONFLICT (id) DO NOTHING;

-- Create RLS policies for settings
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Allow public read access to settings
CREATE POLICY "Public can read settings"
  ON settings
  FOR SELECT
  TO public
  USING (true);

-- Allow authenticated users (admins) to update settings
-- Note: In a real app, you'd want to restrict this to specific admin roles
CREATE POLICY "Admins can update settings"
  ON settings
  FOR UPDATE
  TO authenticated
  USING (true);

-- Allow admins to insert (usually just for initial setup)
CREATE POLICY "Admins can insert settings"
  ON settings
  FOR INSERT
  TO authenticated
  WITH CHECK (true);
